name: write_down_dota_hero
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # AGI HERO
    - assets/heroes/agi/am.png
    - assets/heroes/agi/arch.png
    - assets/heroes/agi/bh.png
    - assets/heroes/agi/brood.png
    - assets/heroes/agi/bs.png
    - assets/heroes/agi/clinkz.png
    - assets/heroes/agi/drow.png
    - assets/heroes/agi/druid.png
    - assets/heroes/agi/ember.png
    - assets/heroes/agi/gyro.png
    - assets/heroes/agi/jugg.png
    - assets/heroes/agi/luna.png
    - assets/heroes/agi/medusa.png
    - assets/heroes/agi/meepo.png
    - assets/heroes/agi/mirana.png
    - assets/heroes/agi/mk.png
    - assets/heroes/agi/morp.png
    - assets/heroes/agi/naga.png
    - assets/heroes/agi/nyx.png
    - assets/heroes/agi/pa.png
    - assets/heroes/agi/pango.png
    - assets/heroes/agi/pl.png
    - assets/heroes/agi/razor.png
    - assets/heroes/agi/riki.png
    - assets/heroes/agi/sf.png
    - assets/heroes/agi/sniper.png
    - assets/heroes/agi/spectre.png
    - assets/heroes/agi/ta.png
    - assets/heroes/agi/tb.png
    - assets/heroes/agi/troll.png
    - assets/heroes/agi/urza.png
    - assets/heroes/agi/venge.png
    - assets/heroes/agi/venom.png
    - assets/heroes/agi/viper.png
    - assets/heroes/agi/void.png
    - assets/heroes/agi/weaver.png
    # INT HERO
    - assets/heroes/int/aa.png
    - assets/heroes/int/bane.png
    - assets/heroes/int/batrider.png
    - assets/heroes/int/cm.png
    - assets/heroes/int/darkseer.png
    - assets/heroes/int/dazzle.png
    - assets/heroes/int/distruptor.png
    - assets/heroes/int/dp.png
    - assets/heroes/int/enchan.png
    - assets/heroes/int/enigma.png
    - assets/heroes/int/invoker.png
    - assets/heroes/int/kotl.png
    - assets/heroes/int/leshrac.png
    - assets/heroes/int/lich.png
    - assets/heroes/int/lina.png
    - assets/heroes/int/lion.png
    - assets/heroes/int/necro.png
    - assets/heroes/int/np.png
    - assets/heroes/int/od.png
    - assets/heroes/int/ogre.png
    - assets/heroes/int/oracle.png
    - assets/heroes/int/puck.png
    - assets/heroes/int/pugna.png
    - assets/heroes/int/qop.png
    - assets/heroes/int/rubick.png
    - assets/heroes/int/shadowdemon.png
    - assets/heroes/int/silencer.png
    - assets/heroes/int/sky.png
    - assets/heroes/int/ss.png
    - assets/heroes/int/techies.png
    - assets/heroes/int/tinker.png
    - assets/heroes/int/visage.png
    - assets/heroes/int/warlock.png
    - assets/heroes/int/wd.png
    - assets/heroes/int/willow.png
    - assets/heroes/int/wind.png
    - assets/heroes/int/ww.png
    - assets/heroes/int/zeus.png
    # STR HERO
    - assets/heroes/str/abbadon.png
    - assets/heroes/str/alchemist.png
    - assets/heroes/str/axe.png
    - assets/heroes/str/beastmaster.png
    - assets/heroes/str/brewmaster.png
    - assets/heroes/str/bristleback.png
    - assets/heroes/str/centaur.png
    - assets/heroes/str/ck.png
    - assets/heroes/str/clockwerk.png
    - assets/heroes/str/dk.png
    - assets/heroes/str/doom.png
    - assets/heroes/str/earthseeker.png
    - assets/heroes/str/elder.png
    - assets/heroes/str/es.png
    - assets/heroes/str/huskar.png
    - assets/heroes/str/io.png
    - assets/heroes/str/kunkka.png
    - assets/heroes/str/lc.png
    - assets/heroes/str/lifestealer.png
    - assets/heroes/str/lycan.png
    - assets/heroes/str/magnus.png
    - assets/heroes/str/ns.png
    - assets/heroes/str/omni.png
    - assets/heroes/str/phonenix.png
    - assets/heroes/str/pudge.png
    - assets/heroes/str/sandking.png
    - assets/heroes/str/sb.png
    - assets/heroes/str/sladar.png
    - assets/heroes/str/sven.png
    - assets/heroes/str/tidehunter.png
    - assets/heroes/str/timbersaw.png
    - assets/heroes/str/tiny.png
    - assets/heroes/str/treant.png
    - assets/heroes/str/tusk.png
    - assets/heroes/str/underlord.png
    - assets/heroes/str/undying.png
    - assets/heroes/str/wk.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
